ARG TARGETPLATFORM=linux/amd64
FROM --platform=${TARGETPLATFORM} ubuntu:22.04

# Download and install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    perl \
    r-cran-devtools \
    wget \
    unzip \
    python3 \
    python3-pip \
    r-base \
    build-essential \
    zlib1g-dev \
    locales

# Configure locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Download and install PLINK 1.9 and 2
## NOTE: The PLINK2 AWS resource URL is subject to change; it looks like they remove old versions
##       once a year or so. Check the bucket URL(s) if either link doesn't work: 
##       https://s3.amazonaws.com/plink1-assets or https://s3.amazonaws.com/plink2-assets

RUN wget https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20230116.zip && \
    unzip plink_linux_x86_64_20230116.zip && \
    mv plink /bin/plink1.9 && \
    rm plink_linux_x86_64_20230116.zip

RUN wget -O plink2_data.zip https://s3.amazonaws.com/plink2-assets/alpha5/plink2_linux_x86_64_20250609.zip && \
    unzip plink2_data.zip && \
    mv plink2 /bin/plink2 && \
    rm plink2_data.zip

# Install Ghostscript -- TBD

WORKDIR /usr/src

COPY . .

# symbolic link to 'old' plink 
RUN ln -s /bin/plink1.9 /bin/plink

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh
    
# Add conda to PATH
ENV PATH="/opt/conda/bin:${PATH}"

# accept TOS
RUN conda config --set channel_priority flexible && \
    echo "channels:" > ~/.condarc && \
    echo "  - conda-forge" >> ~/.condarc && \
    echo "  - defaults" >> ~/.condarc && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

# Create env with compatible python version
RUN conda create -n compadre python=3.11 -y

# Activate the environment and install packages
RUN conda install -n compadre -y -c conda-forge \
    pandas \
    numpy \
    scipy \
    matplotlib \
    scikit-learn \
    xopen

# Make sure the compadre environment is activated by default
ENV PATH="/opt/conda/envs/compadre/bin:${PATH}"

## IN PROGRESS: install reference data from github releases URL 
RUN wget https://github.com/belowlab/compadre/releases/download/pre-release-0.2.0/compadre_data.zip && \
    unzip compadre_data.zip && \
    rm compadre_data.zip

## after downloading, move things according accordingly 
RUN mv compadre_data/1KG /usr/src/lib && \
    mv compadre_data/hapmap3 /usr/src/lib && \
    mv compadre_data/KDE_data /usr/src/lib && \
    mv compadre_data/example_data .

# clean up unzipped empty folders
RUN rm -r __MACOSX && rm -r compadre_data

# Install the KernSmooth R package
RUN Rscript -e "install.packages('KernSmooth', repos='http://cran.rstudio.com/')"

# Add perl path to where primus is expecting it 
RUN mkdir -p /usr/src/perl
ENV PERL_PATH=/usr/src/perl
ENV PERL5LIB=$PERL_PATH:$PERL_PATH/lib/perl5:/usr/src/lib/perl_modules/:/usr/src/lib/perl_modules/PRIMUS/:/usr/src/padre/lib/perl_modules/PADRE:$PERL5LIB

# Change this if you need to use a different port
EXPOSE 6000

ENV COMPADRE_HOST=0.0.0.0

# Set primus executable entrypoint
WORKDIR /usr/src/bin
# This is slightly redundant, but singularity doesn't work otherwise
ENTRYPOINT ["perl", "/usr/src/bin/run_COMPADRE.pl"] 